# Generated by Django 5.2.9 on 2025-12-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SpiderInfo",
            fields=[
                (
                    "spider_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="爬虫ID"
                    ),
                ),
                (
                    "spider_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="爬虫名称"
                    ),
                ),
                (
                    "target_site",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="目标网站"
                    ),
                ),
                ("total_count", models.IntegerField(default=0, verbose_name="累计爬取数量")),
                ("run_count", models.IntegerField(default=0, verbose_name="运行次数")),
                (
                    "last_run_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后运行时间"),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "空闲"), (1, "运行中")], default=0, verbose_name="状态"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "爬虫信息",
                "verbose_name_plural": "爬虫信息",
                "db_table": "spider_info",
            },
        ),
    ]
