# Generated by Django 6.0.4 on 2026-04-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spider", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="spiderinfo",
            name="last_new_count",
            field=models.IntegerField(default=0, verbose_name="本次新增数量"),
        ),
    ]
