# Generated by Django 4.2.7 on 2026-02-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=20, verbose_name="用户ID")),
                ("report_data", models.JSONField(verbose_name="报告数据")),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="生成时间"),
                ),
            ],
            options={
                "verbose_name": "Agent报告",
                "verbose_name_plural": "Agent报告",
                "db_table": "agent_report",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="UserFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=20, verbose_name="用户ID")),
                ("job_id", models.CharField(max_length=50, verbose_name="职位ID")),
                ("feedback_type", models.CharField(max_length=20, verbose_name="反馈类型")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="反馈时间"),
                ),
            ],
            options={
                "verbose_name": "用户反馈",
                "verbose_name_plural": "用户反馈",
                "db_table": "user_feedback",
                "ordering": ["-created_at"],
            },
        ),
    ]
