# Generated by Django 4.2.7 on 2026-02-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI (GPT)"),
                            ("claude", "Claude (Anthropic)"),
                            ("wenxin", "文心一言 (百度)"),
                            ("none", "不使用大模型"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="提供商",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="API Key"
                    ),
                ),
                (
                    "secret_key",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Secret Key（文心一言）",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        default="gpt-3.5-turbo", max_length=100, verbose_name="模型名称"
                    ),
                ),
                (
                    "base_url",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Base URL（可选，用于代理）",
                    ),
                ),
                ("enabled", models.BooleanField(default=False, verbose_name="是否启用")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "大模型配置",
                "verbose_name_plural": "大模型配置",
                "db_table": "llm_config",
            },
        ),
    ]
