# Generated by Django 4.2.7 on 2026-04-10 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0004_alter_jobdata_city_alter_jobdata_company_and_more"),
        ("agent", "0002_llmconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(db_index=True, max_length=20)),
                ("role", models.CharField(max_length=10)),
                ("content", models.TextField()),
                ("intent", models.CharField(blank=True, max_length=30, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "chat_session",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["user_id", "created_at"],
                        name="chat_sessio_user_id_d7b086_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="JobNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(db_index=True, max_length=20)),
                ("match_score", models.IntegerField(default=0)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jobs.jobdata"
                    ),
                ),
            ],
            options={
                "db_table": "job_notification",
                "ordering": ["-created_at"],
                "unique_together": {("user_id", "job")},
            },
        ),
    ]
