# Generated by Django 5.2.9 on 2025-12-18 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobData",
            fields=[
                (
                    "job_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="职位ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="职位名称")),
                (
                    "salary",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="薪资范围"
                    ),
                ),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="最低薪资",
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="最高薪资",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="工作地点"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="城市"
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="学历要求"
                    ),
                ),
                (
                    "experience",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="工作经验"
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="公司名称"
                    ),
                ),
                (
                    "company_type",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="公司类型"
                    ),
                ),
                (
                    "scale",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="公司规模"
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="所属行业"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="职位标签"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="职位描述"),
                ),
                (
                    "href",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="原始链接"
                    ),
                ),
                (
                    "key_word",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="搜索关键词"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="前程无忧", max_length=50, verbose_name="数据来源"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="爬取时间"),
                ),
            ],
            options={
                "verbose_name": "招聘信息",
                "verbose_name_plural": "招聘信息",
                "db_table": "job_data",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserExpect",
            fields=[
                (
                    "expect_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="意向ID"
                    ),
                ),
                (
                    "key_word",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="期望职位"
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="期望地点"
                    ),
                ),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="期望最低薪资",
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="期望最高薪资",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.userlist",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "求职意向",
                "verbose_name_plural": "求职意向",
                "db_table": "user_expect",
            },
        ),
        migrations.CreateModel(
            name="SendList",
            fields=[
                (
                    "send_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="投递ID"
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "已投递"), (1, "已查看"), (2, "邀请面试"), (3, "不合适")],
                        default=0,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="投递时间"),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.jobdata",
                        verbose_name="职位",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.userlist",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "投递记录",
                "verbose_name_plural": "投递记录",
                "db_table": "send_list",
                "unique_together": {("user", "job")},
            },
        ),
    ]
