# Generated by Django 4.2.7 on 2026-02-03 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteJob",
            fields=[
                (
                    "favorite_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="收藏ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="收藏时间"),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.jobdata",
                        verbose_name="职位",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.userlist",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "职位收藏",
                "verbose_name_plural": "职位收藏",
                "db_table": "favorite_job",
                "ordering": ["-created_at"],
                "unique_together": {("user", "job")},
            },
        ),
    ]
