# Generated by Django 4.2.7 on 2026-02-03 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        ("jobs", "0002_favoritejob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sendlist",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    (0, "已投递"),
                    (1, "已查看"),
                    (2, "邀请面试"),
                    (3, "不合适"),
                    (4, "已Offer"),
                ],
                default=0,
                verbose_name="状态",
            ),
        ),
        migrations.CreateModel(
            name="UserExpectItem",
            fields=[
                (
                    "expect_item_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="意向项ID"
                    ),
                ),
                (
                    "key_word",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="期望职位"
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="期望地点"
                    ),
                ),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="期望最低薪资",
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="期望最高薪资",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.userlist",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "求职意向项",
                "verbose_name_plural": "求职意向项",
                "db_table": "user_expect_item",
                "ordering": ["-updated_at"],
            },
        ),
    ]
