# Generated by Django 4.2.7 on 2026-02-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_alter_sendlist_status_userexpectitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobdata",
            name="city",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, null=True, verbose_name="城市"
            ),
        ),
        migrations.AlterField(
            model_name="jobdata",
            name="company",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="公司名称",
            ),
        ),
        migrations.AlterField(
            model_name="jobdata",
            name="company_type",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name="公司类型",
            ),
        ),
        migrations.AlterField(
            model_name="jobdata",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="爬取时间"
            ),
        ),
        migrations.AlterField(
            model_name="jobdata",
            name="education",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, null=True, verbose_name="学历要求"
            ),
        ),
        migrations.AlterField(
            model_name="jobdata",
            name="experience",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name="工作经验",
            ),
        ),
        migrations.AlterField(
            model_name="jobdata",
            name="industry",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name="所属行业",
            ),
        ),
        migrations.AlterField(
            model_name="jobdata",
            name="key_word",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name="搜索关键词",
            ),
        ),
        migrations.AlterField(
            model_name="jobdata",
            name="place",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name="工作地点",
            ),
        ),
        migrations.AlterField(
            model_name="jobdata",
            name="salary_max",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="最高薪资",
            ),
        ),
        migrations.AlterField(
            model_name="jobdata",
            name="salary_min",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="最低薪资",
            ),
        ),
        migrations.AlterField(
            model_name="jobdata",
            name="scale",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name="公司规模",
            ),
        ),
    ]
