# Generated by Django 5.2.10 on 2026-05-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_alter_jobdata_city_alter_jobdata_company_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sendlist",
            name="cover_letter",
            field=models.TextField(blank=True, null=True, verbose_name="求职信"),
        ),
        migrations.AddField(
            model_name="sendlist",
            name="email_sent",
            field=models.BooleanField(default=False, verbose_name="是否已发邮件"),
        ),
    ]
