# Generated by Django 5.2.10 on 2026-05-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SkillMapping",
            fields=[
                (
                    "mapping_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="映射ID"
                    ),
                ),
                (
                    "skill_id",
                    models.IntegerField(
                        db_index=True, unique=True, verbose_name="技能ID"
                    ),
                ),
                (
                    "skill_name",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="技能名称"
                    ),
                ),
                (
                    "local_keyword",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="本地关键词"
                    ),
                ),
                ("confidence", models.FloatField(default=1.0, verbose_name="匹配置信度")),
                (
                    "is_manual",
                    models.BooleanField(default=False, verbose_name="是否手动映射"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "技能映射",
                "verbose_name_plural": "技能映射",
                "db_table": "skill_mapping",
            },
        ),
        migrations.CreateModel(
            name="HistoricalJobData",
            fields=[
                (
                    "hist_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="历史数据ID"
                    ),
                ),
                (
                    "skill_name",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="技能名称"
                    ),
                ),
                ("skill_id", models.IntegerField(db_index=True, verbose_name="技能ID")),
                ("year", models.IntegerField(db_index=True, verbose_name="年份")),
                ("month", models.IntegerField(db_index=True, verbose_name="月份")),
                ("date", models.DateField(db_index=True, verbose_name="日期")),
                ("demand_count", models.IntegerField(verbose_name="需求数量")),
                (
                    "demand_proportion",
                    models.FloatField(blank=True, null=True, verbose_name="需求占比"),
                ),
                (
                    "occupation_l1",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        verbose_name="一级职业",
                    ),
                ),
                (
                    "occupation_l2",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        verbose_name="二级职业",
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=200,
                        null=True,
                        verbose_name="公司",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        verbose_name="地区",
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        default="Job-SDF", max_length=50, verbose_name="数据来源"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="导入时间"),
                ),
            ],
            options={
                "verbose_name": "历史招聘数据",
                "verbose_name_plural": "历史招聘数据",
                "db_table": "historical_job_data",
                "indexes": [
                    models.Index(
                        fields=["skill_name", "date"],
                        name="historical__skill_n_682129_idx",
                    ),
                    models.Index(
                        fields=["occupation_l2", "date"],
                        name="historical__occupat_a7f19e_idx",
                    ),
                    models.Index(
                        fields=["year", "month"], name="historical__year_788ecb_idx"
                    ),
                ],
                "unique_together": {
                    ("skill_id", "year", "month", "occupation_l2", "company", "region")
                },
            },
        ),
        migrations.CreateModel(
            name="SkillCooccurrence",
            fields=[
                (
                    "cooc_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="共现ID"
                    ),
                ),
                (
                    "skill_1_id",
                    models.IntegerField(db_index=True, verbose_name="技能1 ID"),
                ),
                (
                    "skill_1_name",
                    models.CharField(max_length=200, verbose_name="技能1名称"),
                ),
                (
                    "skill_2_id",
                    models.IntegerField(db_index=True, verbose_name="技能2 ID"),
                ),
                (
                    "skill_2_name",
                    models.CharField(max_length=200, verbose_name="技能2名称"),
                ),
                ("frequency", models.IntegerField(verbose_name="共现频率")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "技能共现",
                "verbose_name_plural": "技能共现",
                "db_table": "skill_cooccurrence",
                "indexes": [
                    models.Index(
                        fields=["skill_1_id", "-frequency"],
                        name="skill_coocc_skill_1_e3ace0_idx",
                    ),
                    models.Index(
                        fields=["skill_2_id", "-frequency"],
                        name="skill_coocc_skill_2_510632_idx",
                    ),
                ],
                "unique_together": {("skill_1_id", "skill_2_id")},
            },
        ),
    ]
