# Generated by Django 4.2.7 on 2026-04-10 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlist",
            name="resume_file",
            field=models.FileField(
                blank=True, null=True, upload_to="resumes/", verbose_name="简历文件"
            ),
        ),
        migrations.AddField(
            model_name="userlist",
            name="resume_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="简历文件名"
            ),
        ),
        migrations.AddField(
            model_name="userlist",
            name="resume_updated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="简历更新时间"),
        ),
        migrations.CreateModel(
            name="UserWorkExperience",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="公司名称"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="职位名称"
                    ),
                ),
                (
                    "start_date",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "end_date",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="工作描述"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_experiences",
                        to="users.userlist",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作经历",
                "db_table": "user_work_experience",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="UserEducation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "school",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="学校名称"
                    ),
                ),
                (
                    "degree",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="学历"
                    ),
                ),
                (
                    "major",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="专业"
                    ),
                ),
                (
                    "start_date",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "end_date",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="结束时间"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educations",
                        to="users.userlist",
                    ),
                ),
            ],
            options={
                "verbose_name": "教育经历",
                "db_table": "user_education",
                "ordering": ["-start_date"],
            },
        ),
    ]
